32 plants discover page
demeter-project/demeter-fe pull request #47
Opened 2022-11-06 17:36 UTC by ajkrumholz

### User Story Implemented
#32 Plant Discover Page
### Describe Features Added/Changed

### Describe Tests Added/Changed

### Checklist before requesting a review
- [ ] Added features have thorough tests written for their functionality?
- [ ] All Tests Passing?

2022-11-06 18:44 UTC, musselmanth submitted a review, later dismissed
Part of this user story is the creation of plot plants when the button is pushed. AJ is going to implement that and repush before we review and merge.

2022-11-06 18:59 UTC, sjmann2 commented on app/facades/garden_facade.rb
> +    json[:data].map { |garden| GardenPoro.new(garden[:attributes], garden[:id])}
This is just Garden.new now

2022-11-06 19:05 UTC, sjmann2 requested changes

2022-11-06 19:05 UTC, sjmann2 commented on app/facades/garden_facade.rb
> +    json[:data].map { |garden| GardenPoro.new(garden[:attributes], garden[:id])}
This is just Garden.new now

2022-11-06 19:05 UTC, sjmann2 commented on app/views/plants/index.html.erb
> +
great implementation of a table love that

2022-11-07 14:29 UTC, sjmann2 approved these changes

2022-11-07 14:32 UTC, merged